server:
  port: 5611

spring:
  application:
    name: yuqing-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

## 向服务中心注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mail:
  account: report@yuwoyg.com
  password: sytc123456!
  host: smtp.yuwoyg.com
  from: 舆我有关
  to: 舆情客户