
spring:
  application:
    name: yuqing-service

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 5611

## 向服务中心注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
