spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      routes:
      - id:  apiuser
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://user-service
        predicates:
        # 重点！转发该路径！,/userapi/**,
        - Path=/userapi/**
        # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
        #而不是我们期望的去掉userapi，只保留**部分
        filters:
        - StripPrefix=1
      - id:  api2user
        uri: lb://user-service
        predicates:
        - Path=/userapi2/**
        filters:
        - StripPrefix=1

server:
  port: 5678

## 向服务中心注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
