# gateway 在服务中心注册之后，会为其它的服务默认的生成route，只不过服务名称需要大写[大写服务id+path]的格式
spring:
  cloud:
    gateway:
      routes:
      - id: yuqing-service
        uri: lb://yuqing-service
        predicates:
        - Path=/yuqing-service/**
        # 过滤的order,根据顺序依次过滤
        filters:
        # 注意配置的格式，熔断器配置，当然还可以自己写，继承AbstractGatewayFilterFactory
        - name: Hystrix
          args:
            name: errorFallback
            fallbackUri: forward:/fallback
        - StripPrefix=1
        - Login=true
        - WebToken=true
        # 给这个过滤条
      # 表示注册中心生效
      discovery:
        locator:
          enabled: true
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000