server:
  port: 5613

spring:
  application:
    name: monitor-server
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

## 向服务中心注册服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
